// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVlrnvyPD5Hh46Yek-jqnZYw_xDMVes4',
    appId: '1:551757657693:web:f260a92508db15aca43fb4',
    messagingSenderId: '551757657693',
    projectId: 'tft-ladder-race',
    authDomain: 'tft-ladder-race.firebaseapp.com',
    storageBucket: 'tft-ladder-race.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmYDT2Ao7jftIWCJaOKWiUlew0yWk74Kg',
    appId: '1:551757657693:android:ed3f07b0f2ad8c58a43fb4',
    messagingSenderId: '551757657693',
    projectId: 'tft-ladder-race',
    storageBucket: 'tft-ladder-race.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFViwgf6xlcnW0PWyqEn4xACoulQx1oVY',
    appId: '1:551757657693:ios:eef686fefa0247efa43fb4',
    messagingSenderId: '551757657693',
    projectId: 'tft-ladder-race',
    storageBucket: 'tft-ladder-race.firebasestorage.app',
    iosBundleId: 'com.weemee.tftLadderRace',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFViwgf6xlcnW0PWyqEn4xACoulQx1oVY',
    appId: '1:551757657693:ios:eef686fefa0247efa43fb4',
    messagingSenderId: '551757657693',
    projectId: 'tft-ladder-race',
    storageBucket: 'tft-ladder-race.firebasestorage.app',
    iosBundleId: 'com.weemee.tftLadderRace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkVlrnvyPD5Hh46Yek-jqnZYw_xDMVes4',
    appId: '1:551757657693:web:3ed31d73700f8b13a43fb4',
    messagingSenderId: '551757657693',
    projectId: 'tft-ladder-race',
    authDomain: 'tft-ladder-race.firebaseapp.com',
    storageBucket: 'tft-ladder-race.firebasestorage.app',
  );
}
